# Import library and import data

In [2]:
import chess
import chess.pgn as pgn
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
import os

# ETL data

In [3]:
players = ['Caruana', 'Polgar', 'Fischer', 'Morphy', 'Botvinnik', 'Tal',
 'Kasparov', 'Anand', 'Carlsen', 'Nakamura', 'Alekhine', 'Capablanca']

In [4]:
white_chess_pieces = ['P', 'R', 'N', 'B', 'Q']
mapp = {'P': [0] * 400, 'N': [0] * 400, 'B': [0] * 400, 'R': [0] * 400, 'Q': [0] * 400}

for player in players:
  gameList = os.listdir('../raw_game/' + player)
  for game in gameList:
    gameLink = '../raw_game/' + player + '/' + game
    
    pgn = open(gameLink)

    first_game = chess.pgn.read_game(pgn)
    board = first_game.board()
    

    for turn, move in enumerate(first_game.mainline_moves()):
      board.push(move)
      for piece in white_chess_pieces:
        mapp[piece][turn] += str(board).count(piece)

white_data = pd.DataFrame(mapp)

In [5]:
black_chess_pieces = ['p', 'r', 'n', 'b', 'q']
mapp = {'p': [0] * 400, 'n': [0] * 400, 'b': [0] * 400, 'r': [0] * 400, 'q': [0] * 400}

for player in players:
  gameList = os.listdir('../raw_game/' + player)
  for game in gameList:
    gameLink = '../raw_game/' + player + '/' + game
    
    pgn = open(gameLink)

    first_game = chess.pgn.read_game(pgn)
    board = first_game.board()
    

    for turn, move in enumerate(first_game.mainline_moves()):
      board.push(move)
      for piece in black_chess_pieces:
        mapp[piece][turn] += str(board).count(piece)

black_data = pd.DataFrame(mapp)

In [17]:
piece_data = white_data.join(black_data)
piece_data.insert(loc=0, column = 'Turn', value = range(1, len(piece_data) + 1))
piece_data.to_csv('../analysis/piece-analysis.csv', index=False)

# Visualize your data to make analysis

In [30]:
# There are 21392 valid game in this dataset so we div
piece_data.iloc[:, 1:11] = piece_data.iloc[:, 1:11].div(21392)

In [31]:
piece_data

     Turn         P    N    B    R    Q         p         n    b    r    q
0       1  8.000000  2.0  2.0  2.0  1.0  8.000000  2.000000  2.0  2.0  1.0
1       2  8.000000  2.0  2.0  2.0  1.0  8.000000  2.000000  2.0  2.0  1.0
2       3  8.000000  2.0  2.0  2.0  1.0  7.993876  2.000000  2.0  2.0  1.0
3       4  7.978263  2.0  2.0  2.0  1.0  7.993876  2.000000  2.0  2.0  1.0
4       5  7.978263  2.0  2.0  2.0  1.0  7.959144  1.998831  2.0  2.0  1.0
..    ...       ...  ...  ...  ...  ...       ...       ...  ...  ...  ...
395   396  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0
396   397  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0
397   398  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0
398   399  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0
399   400  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0

[400 rows x 11 columns]